2025-02-21 18:08:39,530 - MainThread - sqlmesh.core.config.connection - INFO - Creating new DuckDB adapter for data files: {'database.duckdb'} (connection.py:309)
2025-02-21 18:08:39,903 - MainThread - sqlmesh.core.config.connection - INFO - Creating new DuckDB adapter for in-memory database (connection.py:311)
2025-02-21 18:08:39,919 - MainThread - sqlmesh.core.config.connection - INFO - Using existing DuckDB adapter due to overlapping data file: database.duckdb (connection.py:305)
2025-02-21 18:08:42,250 - MainThread - sqlmesh.core.snapshot.evaluator - INFO - Listing data objects in schema database.sqlmesh__sqlmesh_example (evaluator.py:322)
2025-02-21 18:08:42,252 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT CURRENT_CATALOG() (base.py:2087)
2025-02-21 18:08:42,253 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT CURRENT_CATALOG() (base.py:2087)
2025-02-21 18:08:42,255 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT table_name AS name, table_schema AS schema, CASE table_type WHEN 'BASE TABLE' THEN 'table' WHEN 'VIEW' THEN 'view' WHEN 'LOCAL TEMPORARY' THEN 'table' END AS type FROM system.information_schema.tables WHERE (table_catalog = 'database' AND table_schema = 'sqlmesh__sqlmesh_example') AND table_name IN ('sqlmesh_example__incremental_model__1127904061', 'sqlmesh_example__seed_model__2185867172', 'sqlmesh_example__full_model__3362895704') (base.py:2087)
2025-02-21 18:08:42,282 - MainThread - sqlmesh.core.snapshot.evaluator - INFO - Listing data objects in schema database.sqlmesh__main (evaluator.py:322)
2025-02-21 18:08:42,283 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT CURRENT_CATALOG() (base.py:2087)
2025-02-21 18:08:42,283 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT CURRENT_CATALOG() (base.py:2087)
2025-02-21 18:08:42,284 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT table_name AS name, table_schema AS schema, CASE table_type WHEN 'BASE TABLE' THEN 'table' WHEN 'VIEW' THEN 'view' WHEN 'LOCAL TEMPORARY' THEN 'table' END AS type FROM system.information_schema.tables WHERE (table_catalog = 'database' AND table_schema = 'sqlmesh__main') AND table_name IN ('main__raw_accounts__31813219', 'main__raw_accounts__31813219__dev') (base.py:2087)
2025-02-21 18:08:42,289 - MainThread - sqlmesh.core.state_sync.engine_adapter - INFO - Promoting environment 'prod' (engine_adapter.py:280)
2025-02-21 18:08:42,303 - MainThread - sqlmesh.core.snapshot.evaluator - INFO - Creating schema 'database.sqlmesh_example' (evaluator.py:1060)
2025-02-21 18:08:42,303 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE SCHEMA IF NOT EXISTS "database"."sqlmesh_example" (base.py:2087)
2025-02-21 18:08:42,303 - MainThread - sqlmesh.core.snapshot.evaluator - INFO - Creating schema 'database.main' (evaluator.py:1060)
2025-02-21 18:08:42,304 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE SCHEMA IF NOT EXISTS "database"."main" (base.py:2087)
2025-02-21 18:08:42,304 - MainThread - sqlmesh.core.snapshot.evaluator - INFO - Updating view 'database.main.raw_accounts' to point at table 'database.sqlmesh__main.main__raw_accounts__31813219' (evaluator.py:1367)
2025-02-21 18:08:42,304 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE OR REPLACE VIEW "database"."main"."raw_accounts" AS SELECT * FROM "database"."sqlmesh__main"."main__raw_accounts__31813219" (base.py:2087)
2025-02-21 18:08:42,306 - MainThread - sqlmesh.core.context - INFO - Plan application failed. (context.py:1418)
Traceback (most recent call last):
  File "/Users/tiagonavarro/.pyenv/versions/3.10.13/lib/python3.10/site-packages/sqlmesh/utils/concurrency.py", line 227, in sequential_apply_to_dag
    fn(node)
  File "/Users/tiagonavarro/.pyenv/versions/3.10.13/lib/python3.10/site-packages/sqlmesh/utils/concurrency.py", line 165, in <lambda>
    lambda s_id: fn(snapshots_by_id[s_id]),
  File "/Users/tiagonavarro/.pyenv/versions/3.10.13/lib/python3.10/site-packages/sqlmesh/core/snapshot/evaluator.py", line 242, in <lambda>
    lambda s: self._promote_snapshot(
  File "/Users/tiagonavarro/.pyenv/versions/3.10.13/lib/python3.10/site-packages/sqlmesh/core/snapshot/evaluator.py", line 919, in _promote_snapshot
    _evaluation_strategy(snapshot, adapter).promote(
  File "/Users/tiagonavarro/.pyenv/versions/3.10.13/lib/python3.10/site-packages/sqlmesh/core/snapshot/evaluator.py", line 1368, in promote
    self.adapter.create_view(
  File "/Users/tiagonavarro/.pyenv/versions/3.10.13/lib/python3.10/site-packages/sqlmesh/core/engine_adapter/shared.py", line 302, in internal_wrapper
    return func(*list_args, **kwargs)
  File "/Users/tiagonavarro/.pyenv/versions/3.10.13/lib/python3.10/site-packages/sqlmesh/core/engine_adapter/base.py", line 1054, in create_view
    self.execute(
  File "/Users/tiagonavarro/.pyenv/versions/3.10.13/lib/python3.10/site-packages/sqlmesh/core/engine_adapter/base.py", line 2084, in execute
    self._execute(sql, **kwargs)
  File "/Users/tiagonavarro/.pyenv/versions/3.10.13/lib/python3.10/site-packages/sqlmesh/core/engine_adapter/base.py", line 2090, in _execute
    self.cursor.execute(sql, **kwargs)
duckdb.duckdb.CatalogException: Catalog Error: Existing object raw_accounts is of type Table, trying to replace with type View

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tiagonavarro/.pyenv/versions/3.10.13/lib/python3.10/site-packages/sqlmesh/core/context.py", line 1410, in apply
    self._apply(plan, circuit_breaker)
  File "/Users/tiagonavarro/.pyenv/versions/3.10.13/lib/python3.10/site-packages/sqlmesh/core/context.py", line 1989, in _apply
    self._scheduler.create_plan_evaluator(self).evaluate(
  File "/Users/tiagonavarro/.pyenv/versions/3.10.13/lib/python3.10/site-packages/sqlmesh/core/plan/evaluator.py", line 141, in evaluate
    self._update_views(
  File "/Users/tiagonavarro/.pyenv/versions/3.10.13/lib/python3.10/site-packages/sqlmesh/core/plan/evaluator.py", line 338, in _update_views
    self._promote_snapshots(
  File "/Users/tiagonavarro/.pyenv/versions/3.10.13/lib/python3.10/site-packages/sqlmesh/core/plan/evaluator.py", line 368, in _promote_snapshots
    self.snapshot_evaluator.promote(
  File "/Users/tiagonavarro/.pyenv/versions/3.10.13/lib/python3.10/site-packages/sqlmesh/core/snapshot/evaluator.py", line 240, in promote
    concurrent_apply_to_snapshots(
  File "/Users/tiagonavarro/.pyenv/versions/3.10.13/lib/python3.10/site-packages/sqlmesh/utils/concurrency.py", line 163, in concurrent_apply_to_snapshots
    return concurrent_apply_to_dag(
  File "/Users/tiagonavarro/.pyenv/versions/3.10.13/lib/python3.10/site-packages/sqlmesh/utils/concurrency.py", line 198, in concurrent_apply_to_dag
    return sequential_apply_to_dag(dag, fn, raise_on_error)
  File "/Users/tiagonavarro/.pyenv/versions/3.10.13/lib/python3.10/site-packages/sqlmesh/utils/concurrency.py", line 233, in sequential_apply_to_dag
    raise error
sqlmesh.utils.concurrency.NodeExecutionFailedError: Execution failed for node SnapshotId<"database"."main"."raw_accounts": 2206870727>
2025-02-21 18:08:42,327 - MainThread - root - INFO - Shutting down the event dispatcher (dispatcher.py:159)
