[2025-02-26T14:44:44.497+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: load_bronze_accounts_deleted.bronze_accounts_deleted_task scheduled__2025-02-25T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
