[2025-02-26T14:54:43.314+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_bronze_accounts_deleted.bronze_accounts_deleted_trigger scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-02-26T14:54:43.318+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_bronze_accounts_deleted.bronze_accounts_deleted_trigger scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-02-26T14:54:43.319+0000] {taskinstance.py:2171} INFO - Starting attempt 5 of 6
[2025-02-26T14:54:43.326+0000] {taskinstance.py:2192} INFO - Executing <Task(SimpleHttpOperator): bronze_accounts_deleted_trigger> on 2025-02-25 00:00:00+00:00
[2025-02-26T14:54:43.329+0000] {standard_task_runner.py:60} INFO - Started process 126 to run task
[2025-02-26T14:54:43.331+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'load_bronze_accounts_deleted', 'bronze_accounts_deleted_trigger', 'scheduled__2025-02-25T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/dynamic_api_trigger.py', '--cfg-path', '/tmp/tmpunz4yhyd']
[2025-02-26T14:54:43.331+0000] {standard_task_runner.py:88} INFO - Job 38: Subtask bronze_accounts_deleted_trigger
[2025-02-26T14:54:43.354+0000] {task_command.py:423} INFO - Running <TaskInstance: load_bronze_accounts_deleted.bronze_accounts_deleted_trigger scheduled__2025-02-25T00:00:00+00:00 [running]> on host 6746a23eb18f
[2025-02-26T14:54:43.390+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_bronze_accounts_deleted' AIRFLOW_CTX_TASK_ID='bronze_accounts_deleted_trigger' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-25T00:00:00+00:00'
[2025-02-26T14:54:43.390+0000] {http.py:169} INFO - Calling HTTP method
[2025-02-26T14:54:43.394+0000] {base.py:83} INFO - Using connection ID 'api_service' for task execution.
[2025-02-26T14:54:43.398+0000] {base.py:83} INFO - Using connection ID 'api_service' for task execution.
[2025-02-26T14:54:43.399+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 166, in execute
    return self.execute_sync(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 170, in execute_sync
    response = self.hook.run(self.endpoint, self.data, self.headers, self.extra_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 145, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 120, in get_conn
    session.headers.update(headers)
  File "/usr/local/lib/python3.8/_collections_abc.py", line 837, in update
    for key, value in other:
ValueError: not enough values to unpack (expected 2, got 1)
[2025-02-26T14:54:43.404+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=load_bronze_accounts_deleted, task_id=bronze_accounts_deleted_trigger, execution_date=20250225T000000, start_date=20250226T145443, end_date=20250226T145443
[2025-02-26T14:54:43.410+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 38 for task bronze_accounts_deleted_trigger (not enough values to unpack (expected 2, got 1); 126)
[2025-02-26T14:54:43.431+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-02-26T14:54:43.440+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
